### ISSUE TITLE
Lähtötietoaineistotaulu "lilluu" mallissa

### ISSUE THREAD

**Issue by SannaJokela** [sykefi/kaavatietomalli#101]
Lähtötietoaineisto-taulu ei linkittynyt mihinkään kaavan muihin tauluihin. Jatkokehityksenä voisi olla hyvä saada se liittymään ainakin kaavakohde-tauluun

**Comment by ilkkarinne** [comment]
AbstraktiMaankayttoasia-luokassa on assosiaatio hyodynnettyAineisto[0..*]:Lahtotietoaineisto, joka periytyy sen aliluokkaan Kaava.

**Comment by SannaJokela** [comment]
Ok, kiitos tiedosta, abstraktimaankäyttöasia on tosiaan jäänyt testauksissa puutteeliseksi, korjataan tämä PostGIS-toteutukseen.
