### ISSUE TITLE
Kaavan laatijoita useampi

### ISSUE THREAD

**Issue by SannaJokela** [sykefi/kaavatietomalli#102]
Kaavan_laatija-tauluun voi kirjata useita henkilöitä, mutta relaatio 1:1 mahdollistaa vain yhden henkilön liittämisen kaavan tietoihin. Onko tarpeen mahdollistaa useita henkilöitä, vai riittääkö pääsuunnittelijan tiedot?

**Comment by ilkkarinne** [comment]
Kaava-luokan laatija-assosiaation kardinaliteetti on 0..*, eli yhdellä kaavalla voi olla monta laatijaa. KaavaLaatija-luokassa on mukana nimen ja nimikkeen lisäksi rooli, jolla ko. toimija on osallistunut laadintaan. Kaavatietomallissa haluttiin nimenomaan välttää tarpeettoman tarkkojen henkilötietojen tuominen tietojärjestelmään, joten nimi voi olla myös organisaation nimi

**Comment by SannaJokela** [comment]
Tämä olikin meidän virhe, pahoittelut ja kiitos tiedoista!
