### ISSUE TITLE
Mahdollinen virhe käsittelytapahtumassa ja vuorovaikutustapahtumassa

### ISSUE THREAD

**Issue by SannaJokela** [sykefi/kaavatietomalli#104]
Käsittelytapahtuma ja vuorovaikutustapahtuma liittyivät mallissa vain asiakirjaan? Milloin ja miten näitä pitäisi käsitellä. UML:n perusteella en saanut selvää.

**Comment by ilkkarinne** [comment]
Kasittelytapahtuma- ja Vuorovaikutustapahtuma-luokkien yhteisella yläluokalla AbstraktiTapahtuma on yksisuuntainen assosiaatio liittyvaAsia[0..*]: AbstraktiMaankayttoasia. Kaava-luokan tapauksessa käsittely- ja vuorovaikutustapahtumat siis liittyvät Kaavaan ko. assosiaatiolla.

Ehkä MKP-ydin paketin sisältämien yläluokkien assosiaatiot ovat jääneet lukijalta tässä ja muutamassa muussakin raportoidussa seikassa huomaamatta?

**Comment by SannaJokela** [comment]
Voipi olla :) Pahoittelut tästä! Tarkistan vielä asiat ja closaan nämä sitten

**Comment by SannaJokela** [comment]
Tarkistettu, abstraktimaankäyttöasiaa ei ole PostGIS-toteutuksessa huomioitu kunnolla, tämä siis testaajien virhe. Closaan tämän.
