### ISSUE TITLE
Toinen Ota kantaa -kysely

### ISSUE THREAD

**Issue by ilkkarinne** [sykefi/kaavatietomalli#14]
**Kuvaus**
Toinen Otakantaa-kysely 1.10.-15.10.2020: Tarkennettu käsitemalli (AK ja YK), koodistot, sanastot, laatu- ja elinkaarisäännöt, soveltamisohjeet

ks. 1. Ota kantaa -kysely (#6)

Tuotokset:

- [ ] Kyselyn kysymykset suunniteltu
- [ ] Ota kantaa -kysely julkaistu ja vastausten yhteenveto laadittu

**Comment by pilvinummi** [comment]
Kysely toteutettaneen lokakuun puolivälissä eli pari viikkoa alkuperäisestä aikataulusta jäljessä.

**Comment by pilvinummi** [comment]
Tehty ja raportoitu
