### ISSUE TITLE
Valittu lisenssi on ohjelmistolisenssi

### ISSUE THREAD

**Issue by posikifi** [sykefi/kaavatietomalli#28]
Tuo valittu MIT on ohjelmistoja koskeva lisenssi.Tietomalli ei liene ohjelmisto. Ehkä CC0 olisi parempi vaihtoehto tälle.

**Comment by ilkkarinne** [comment]
Hyvä huomio. Otetaan keskusteluun YM:n kanssa

**Comment by ilkkarinne** [comment]
Lisenssi nyt Creative Commons Attribution 4.0 International
