### ISSUE TITLE
Yksilöivien tunnuksen muoto

### ISSUE THREAD

**Issue by posikifi** [sykefi/kaavatietomalli#29]
Monessa paikassa oli mainittu, että yksilöivät tunnukset ovat URI muotoa, tällä viitatteneen IETF 3986:n.

INSPIREssä ja JHS193:ssa on päädytty siihen, että yksilöivät tunnukset ovat HTTP URI -muotoisia. Yhtenä perusteluna on ollut mahdollistaa Linked Data-tyyppiset palvelut yms.

Jos päädytty HTTP URI:n käyttöön yksilöivissä tunnuksissa, niin paikkatiedot.fi -tyyppinen uudelleenohjaus palvelun perustaminen olisi toivottavaa. Se voisi olla rytj.fi tai tietysti myös suomi.fi jollakin lisätunnuksilla varustettuna tms.

**Comment by ilkkarinne** [comment]
Itse näkisin parhaimpana käyttää kaavatietojen pysyvinä tunnuksina HTTP URI -muotoisia tunnuksia, ja tuollaisen uudelleenohjauspalvelun lähes välttämättömänä. RYTJ-suunnittelussa pitää ottaa kantaa miten tuo toteutetaan ja mikä on paras pysyvä domain huomioiden sekä pysyvyyden että joustavuuden uusien uudelleenohjaustarpeiden suhteen. Yhteentoimivuusalustan http://uri.suomi.fi/ vaikuttaa minusta hyvältä, mutta en osaa sanoa miten helppoa on määritellä tuon alle RYTJ:n tarvitsemat objektikohtaiset tunnukset ja niille uudelleenohjaussäännöt.
