### ISSUE TITLE
Puuttuva koodi: Mäenlaskupaikka

### ISSUE THREAD

**Issue by pilvinummi** [sykefi/kaavatietomalli#48]
**Käyttötarkoituslaji**
739: Mäenlaskupaikka

**Comment by ilkkarinne** [comment]
Tämä löytyy jo Tarkentavasta käyttötarkoituslajista: http://uri.suomi.fi/codelist/rytj/TarkentavaKayttotarkoitusLaji/code/0208

**Comment by pilvinummi** [comment]
Aivan, olisikin pitänyt käyttää sitä - korjataan siis testiaineistoon tämä määräyskoodi.
