### ISSUE TITLE
Puuttuva koodi: AK: Alue, jolla on erityistä ulkoilun ohjaamistarvetta

### ISSUE THREAD

**Issue by ilkkarinne** [sykefi/kaavatietomalli#52]
YK-kaavamääräyslaji-koodistosta löytyy 0612 - Alue, jolla on erityistä ulkoilun ohjaamistarvetta (http://uri.suomi.fi/codelist/rytj/KaavamaaraysLajiYleiskaava/code/0612), mutta AK-puolelta ei.

**Comment by pilvinummi** [comment]
Lisätty uuteen Asemakaavan kaavamääräyslaji -exceliin
