### ISSUE TITLE
GeoJSON-merge skriptin rakentaminen

### ISSUE THREAD

**Issue by sampov2** [sykefi/kaavatietomalli#53]
Tuotetaan skripti (esim. Python, JS, Bash), joka yhdistää Driveen tehdyt kaavatietofragmentit yhdeksi featurecollectioniksi.

Fragmentit ovat tehty siten, että Drivessa yhdessä kansiossa on kaikki kyseiseen kaavaan liittyvät fragmentit. Fragmentteja on kahdenlaisia:

1. Kaava ja siihen kaavaan suoraan liittyvät kaavamääräykset (1 kpl), kutsutaan jälkeenpäin "A"
2. Kaavakohde ja siihen suoraan liittyvät kaavamääräykset (n kpl), kutsutaan jälkeenpäin "B"

Sekä A:ssa että B:ssä on n kpl kaavamääräyksiä ja 1 kpl featureja (kaava tai kaavakohde), johon kaavamääräykset kohdistuu.

Toimintaperiaate:

**Yhdistäminen tehdään kolmivaiheisena operaationa:**

_Huom! Tässä puhutaan muutoksista, mutta tällä tarkoitetaan ainoastaan muistiin luetun tiedon muokkaamista. Alkuperäisiä tiedostoja Drivessä ei muuteta missään tapauksessa!_

1. Käydään läpi kaikki lähtötiedostot joukossa A ja B ja tehdään seuraavat operaatiot
    - Luodaan juuritason "id" kaikille Featureille lähtötiedoston FeatureCollectionin sisälle
    - Luodaan kunkin FeatureCollectionin sisällä **kaksisuuntainen** linkitys kaavamääräyksestä kaavaan (osajoukko A) tai kaavakohteeseen (osajoukko B). Huom. Tämä onnistuu siksi, että kussakin lähtötiedostossa kaikki kaavamääräykset kohdistuvat tiedostossa olevaan kaavaan tai kaavakohteeseen, joita tiedostoissa on vain 1 kpl

2. Käydään läpi kaikki A:t ja B:t
    - Luodaan linkit B:n kaavakohteesta kaavaan A
    - Luodaan linkit A:n kaavasta kaikkiin B:n kaavakohteisiin

3. Yhdistetään kaikki Featuret (kaava, kaavakohteet, kaavamääräykset) A:sta ja B:stä yhdeksi FeatureCollectioniksi

Lopputulos kirjoitetaan GeoJSON-tiedostoon, missä on FeatureCollection, mikä sisältää lähtöaineistoista ladatut ja edellisessä prosessissa höystetyt featuret. Selkeyden vuoksi: FeatureCollectionin tulee olemaan litteä, jossa kaikki featuret ovat samalla tasolla.

**Comment by sampov2** [comment]
Ping @ilkkarinne - olisi hyvä jos voisit lisätä taskiin tarkat kenttien nimet linkityksille ja mahdollisesti esimerkin linkityksetä.

Tähän liittyen linkityksessä tässä vaiheessa prosessia riittää id:llä viittaaminen, tämän merge-skriptin ei tarvitse rakentaa HTTP-linkkejä - tämä jää upload-prosessin vastuulle.

**Comment by ilkkarinne** [comment]
Linkitysesimerkki, joukko A, kaava ja siihen suoraan liittyvät kaavamääräykset:

Oletetaan että SpatialPlan:in  id = "123345" ja siihen liittyvien PlanRegulation-kohteiden id:t "abcdgf" ja "hkkitf". Tällöin tehtään SpatialPlan-kohteen properties:n alle seuraava ominaisuus:
```json
"generalRegulations": [
                {
                    "linkedFeatureId": "abcdgf"
                },
                {
                    "linkedFeatureId": "hkkitf"
                }
]
```

ja kummmankin PlanRegulation-kohteen properties:in alle seuraava (sama) ominaisuus:
```json
"spatialPlan": {
    "linkedFeatureId": "123345"
}
```

**Comment by ilkkarinne** [comment]
Linkitysesimerkki, joukko B, kaavakohde ja siihen suoraan liittyvät kaavamääräykset:

Oletetaan, että PlanRegulationObject:in id = "9987456" ja siihen liittyvien PlanRegulation-kohteiden id:t "34rjkhgwklfd" ja "9034jergj". Tällöin tehdään PlanRegulationObject-kohteen properties:in alle seuraava ominaisuus:
```json
"regulations": [
                {
                    "linkedFeatureId": "34rjkhgwklfd"
                },
                {
                    "linkedFeatureId": "9034jergj"
                }
]
```

ja kummankin PlanRegulation-kohteen properties:in alle seuraava (sama) ominaisuus:
```json
"targetObject": {
                    "linkedFeatureId": "9987456"
            }
```

**Comment by ilkkarinne** [comment]
> 2. Käydään läpi kaikki A:t ja B:t
>    
>    * Luodaan linkit B:n kaavakohteesta kaavaan A
>    * Luodaan linkit A:n kaavasta kaikkiin B:n kaavakohteisiin

Tähän kohteen lisäisin vielä, että luodaan linkit kaikista B:n kaavamääräyksistä (PlanRegulation) A:n kaavaan (SpatialPlan). Eli ihan kaikissa PlanRegulation-objekteissa (riippumatta ovatko ne alunperin A:ssa vai B:ssä), tulee lopulta olla seuraava ominaisuus properties:n alla:
```json
"spatialPlan": {
    "linkedFeatureId": "123345"
}
```

**Comment by ilkkarinne** [comment]
Ja siis huomiona vielä, että tässä tunnusten generoinnissa populoidaan vain GeoJSON-objektin `id`-kentät, `identityId`, `versionId` ja `localId`-kentille ei tehdä mitään.

Yleisemminkin `linkedFeatureId` viittaa aina kohteen `id`-kentän arvoon
