### ISSUE TITLE
Kaavatiedon versioituminen muutosten yhteydessä

### ISSUE THREAD

**Issue by sampov2** [sykefi/kaavatietomalli#57]
Koska tietomallissa on linkkaus kahteen suuntaan (esim. määräyksestä kaavakohteeseen ja takaisin), johtaa muutokset mihin tahansa kaavan tietomallin osaan versiointiin kaikissa kaavan featureissa.

Esim. Jos kaavakohteeseen liittyvä määräys päivittyy, tulee määräykselle uusi versionumero. Tämä johtaa kohteessa olevan linkin päivittymiseen. Linkin muutos johtaa kohteelle uuteen versionumeroon, joka taas vaikuttaa kaikkiin sen alla olevien määräysten linkkeihin. Koska kohteen versionumero on päivittynyt, tulee myös kaavan linkki kohteeseen päivittyä, joka johtaa kaavan version päivittämiseen joka linkkien kautta johtaa myös muiden kaavakohteiden ja määritysten versioiden päivittymiseen.

Summa summarum: kaksisuuntaisella linkityksellä yksikin muutos johtaa kaikkien kaavan palasten versiointiin. Tällä on negatiivinen seuraus siitä, että on vaikeampi operaatio etsiä todellisuudessa muuttunut osa kaavasta (avatii sisällöllistä vertailua). Tällä on myös positiivisia seurauksia: jos versiointi ei leviäisi kaikkialle, johtaisi esim. kaavakohteen muuttuminen siihen, että edelliseen ja nykyiseen kohteen versioon liittyvää kaavamääräystä tulisi päivittää linkittymään molempiin versioihin.

**Comment by ilkkarinne** [comment]
Kyllä, mikäli halutaan tallentaa kantaan ainoastaan muuttuneet kavamääräyskohteet ja kaavamääräykset, johtaa se siihen, että kaavamääräyskohteen yhden version tulisi voida liittyä useampaan kaavan versioon ja vastaavasti kaavamääräyksen yhden version tulisi voida liittyä useampaan kaavamääräyskohteen ja/tai kaavan versioon. Testauksen pohjana olevan UML-mallin version mukaan tämä ei ole mahdollista.

**Comment by ilkkarinne** [comment]
Nykyisessä mallissa  minkä tahansa kaavan sisältämän kaavamääräyskohteen tai kaavamääräyksen (tai sen arvon) muuttaminen johtaa uusien kopioiden luomiseen kaikkien kaavan muistakin kohteista ja määräyksistä, sillä ne viittaavat muuttuvaan kaavan versioon. Näin ollen kukin kaavaprosessin aikainen kaavan tallennusversio on kokonainen uusi kopio koko kaavan sisällöstä, jolloin yksittäisen kaavamääräyskohteen versiohistoria muodostuu siten suurelta osin sisällöltään identtisistä kopioista, ja todellisten muutosten erottaminen pelkästään muuttuneita viittauksia sisältävistä vaatii erillistä logiikkaa.

Ehdotus olisi muuttaa linkitystä siten, että tietomallissa olisi vain "alaspäin" viittaavia linkkejä, eli kaavasta sen kaikkiin yleismääräyksiin ja kaavamääräyskohteisiin, ja kustakin kaavamääräyskohteesta vain yhteen suuntaan kaavamääräyksiin päin. Käytännössä tämä tarkoittaisi, että RYTJ:ään tallennettaisiin ladattavan kaavan version mukana vain ne kaavamääräyskohteet ja kaavamääräykset, jotka  eivät ole identtisiä ko. kohteen tai määräyksen edellisen tallennetun version kanssa. Mikäli objekti on identtinen edellisen version kanssa, voidaan uuden objektin tallentamisen sijaan viitata suoraan jo tallennettuun versioon. Täten kaksi tai useampi saman kaavan tallennusversio voisi viitata samaan kaavamääräyskohteen tai kaavamääräyksen versioon, mikä ei nykyisessä mallissa ole mahdollista. Tästä ei nähdäkseni aiheutuisi hallintaongelmaa, koska kukin kaavan, kohteen tai määräyksen versio on tallennuksen jälkeen muuttumaton, eli niitä ei voi muokata, jolloin ei tarvitse murehtia miten muokkaukset vaikuttavat niihin linkkaaviin tietoihin.

**Comment by ilkkarinne** [comment]
Mikäli kaavamääräyskohde- ja kaavamääräys-luokista poistetaan ylöspäin viittaus kaava-luokkaan, tulee niiden suodattaminen tiettyyn kaavaan liittymisen perusteella vaikeaksi (koska eivät enää sisällä kaava-linkkiä). Toisaalta viittausten muuttaminen pelkästään ylöspäin viittaavaksi ei onnistu luontevasti kaava - kaavamääräyskohde - kaavamääräys -rakenteessa johtuen mahdollisesta kaavamääräyskohteiden tai kaavamääräysten poistumisesta kaavan versioiden välillä: Jos yksittäinen kaavamääräyskohde ei olisi enää mukana seuraavassa tallennusversiossa, se ei näkyisi kaava-objektin muutoksena. Mikäli muuttumattomia kohteita ei tallenneta uusina versioina, viittaavat myös poistuneet kaavamääräyskohteet edelleen (muuttumattomaan) kaava-objektiin yhdessä muuttuneiden ja uusien kaavamääräyskohteiden kanssa.

Ratkaisu tässä vaiheessa voisi olla molemminsuuntainen linkitys, vaikka se johtaakin myös muuttumattomien kaavamääräyskohteiden ja kaavamääräysten uusiin versioihin. Ohjelmallisesti on melko triviaalia tehdä muutospalvelu, joka palauttaa kohteen todellisen muutoshistorian suodattaen pois pelkät tunnusten ja linkitysten muutokset silloin, kun linkitys päivittyy viittaamaan saman kohteen uudempaan versioon (eli identiteettitunnus säilyy).
