### ISSUE TITLE
Koko kaavan palauttava rajapinta vs OGC API - Features

### ISSUE THREAD

**Issue by sampov2** [sykefi/kaavatietomalli#67]
Testasimme tuottaa API Featuresin "mukaista" rajapintaa, mikä palauttaisi kaavan tietomallin kaikkineen tietoineen (kaavan ulkoraja, kohteet ja määräykset). Tämä kuitenkaan ei luonnistu suoraan rajapintamäärityksen mukaisesti, koska API Featuresin collectionin pitäisi palauttaa rakenteeltaan samanlaisia tai vähintään samankaltaisia olioita. Nyt koetettu malli johtaisi collectioniin, joka palauttaisi FeatureCollectionin, jonka sisällä olisi keskenään erilaisia featureita.

Jäi tämän testauksen pohjalta auki, miten parhaiten tehdä API Featuresilla palvelu, josta pystyisi yhdellä operaatiolla hakemaan koko kaavan tiedot.

**Comment by ilkkarinne** [comment]
Mikä tarkalleen ottaen olisi ongelma API Features -kokoelman määritelemisessä siten, että se palauttaa (geneerisiä) GeoJSON FeatureCollection:ieta?

**Comment by ilkkarinne** [comment]
Vastaan itselleni: [RFC 7946;n FeatureCollection]([https://tools.ietf.org/html/rfc7946#section-3.3) on määritelty siten, että sen ```features``` -jäsen on GeoJSON Feature -kohteita sisältävä taulukko. GeoJSON:in FeatureCollection ei ole Feature, joten FeatureCollection ei voi sisältää FeatureCollectionia jäsenenä.
