### ISSUE TITLE
GeoJSON muodossa olevat juuritason tiedot

### ISSUE THREAD

**Issue by sampov2** [sykefi/kaavatietomalli#70]
Joissain ohjelmistokirjastoissa esim. OpenLayers, GeoJSON objektien juuritasolla olevat tiedot katoavat prosessointiketjussa. Näihin ei välttämättä ole järkevä luottaa lopullisessa enkkodausmuodossa.

**Comment by ilkkarinne** [comment]
Tarkoitat siis, että vain ```properties```:n alla olevat tiedot välittyvät OpenLayers:ille? Eli ```featureType``` tulisi siirtää properties:in alle?

**Comment by sampov2** [comment]
Jep. Vain propertiesissa olevat tulevat OpenLayersille. Myös API Featuresin linkit ovat tässä kohtaa haastavia - kun nykyinen visualisointiprototyyppi hakee yksittäiset kohteet, on jokaisella featurella mukana kätevästi linkit kohteisiin. Valitettavasti nekin kuitenkin katoavat openlayersin GeoJSON-prosessoinnin syövereihin.
