### ISSUE TITLE
Abstraktityyppisten olioiden tyyppi GeoJSON enkoodauksessa

### ISSUE THREAD

**Issue by sampov2** [sykefi/kaavatietomalli#78]
Olisi hyödyllistä jos mm. AbstraktiArvo-olioiden ilmentymässä olisi kenttä, jossa on olion tyyppi (TimeInstantValue, TimePeriodValue, GeometryValue, jne.). Ilman tätä tietoa AbstraktiArvo-olion tyyppi pitää päätellä siitä mitä kenttiä JSON-oliossa on. Sama pätee varmasti muihinkin abstrakteihin tyyppeihin.

**Comment by ilkkarinne** [comment]
Tämä oli jo huomattu testauksen aikana, ja lisätty ```valueType```-attribuutti Arvo-luokan alaluokkien JSON-koodauksen määrittelyyn, ks. https://ym-rakennettu-ymparisto.github.io/AK-YK-tietomallit/1.0/fyysiset-mallit/json/#tietotyypit-datatype

Kaava-JSON ei sisällä toteutuksia abstrakteille luokille. Tämä ongelma ilmenee vain ```DataType```-stereotyypin yhteydessä, sillä kaikki ```FeatureType```-assosiaatiot on toteutettu FeatureLink-rakenteen avulla.
