### ISSUE TITLE
Kaavan ulkorajaan voi liittyä asiakirja

### ISSUE THREAD

**Issue by SannaJokela** [sykefi/kaavatietomalli#92]
Puute tietomallissa, oli kuvattu dokumentaatiossa, mutta puuttui UML-mallista https://kaavatietomalli.fi/1.0/kasitemalli/#kaavan-liite

**Comment by ilkkarinne** [comment]
Kaava-luokalla on sen luokasta AbstraktiMaankayttoasia peritty assosiaatio asianLiite[0..*]: Asiakirja, ks. https://kaavatietomalli.fi/1.0/looginenmalli/dokumentaatio/#abstraktimaankayttoasia

**Comment by SannaJokela** [comment]
Ah, tämä oli jäänyt meiltä huomaamatta, koska se ilmeisesti liittyi vain kaava-luokkaan. Korjataan. Kiitos!
