### ISSUE TITLE
Kaavoitusteemoja useampi / kaavamääräys

### ISSUE THREAD

**Issue by SannaJokela** [sykefi/kaavatietomalli#97]
Kaavoitusteemoja voisi olla kaavamääräyksillä useita, tällä hetkellä sallitaan vain yksi.

**Comment by ilkkarinne** [comment]
Kaavamääräys-luokan teema-attribuutin kardinaliteetti on mallissa 0..*, eli yhteen määräykseen voi liittyä nolla tai useampi teema.

**Comment by SannaJokela** [comment]
Ok, tässä oli testauksessa relaatio väärinpäin, pahoittelut.
