### ISSUE TITLE
OAS ja useampi kaava

### ISSUE THREAD

**Issue by SannaJokela** [sykefi/kaavatietomalli#99]
Osallistumis- ja arviointisuunnitelma-taulussa: onko OASin tarpeen liittyä useaan kaavaan, vai onko mallissa/testauksessa tehty virhe?

**Comment by ilkkarinne** [comment]
Tietomallissa OsallistumisJaArviointisuunnitelma-luokalla ei ole muita assosiaatioita kuin asiakirja, eli OAS:n suunnasta ei pääse navigoimaan Kaava-luokkaan päin. Tällä on pyritty välttämään versiointitarpeen leviämistä OAS:iin ja kaavaselostukseen Kaava-luokan tai sen määräysten muuttuessa versionnissa, ks. https://kaavatietomalli.fi/1.0/looginenmalli/elinkaarisaannot.html#muutosten-levi%C3%A4minen-viittausten-kautta

**Comment by SannaJokela** [comment]
Kiitos! Tässä on ollut meidän päässä virhe, pahoittelut!
